import "./css/example.css";
import "./css/MyHobby.css";
import { AppClass } from "./AppClass";
import { Hello } from "./components/Hello"
import { Hobies } from "./components/Hobies"
import { FavoriteHobby } from "./components/FavoriteHobby"
import { MyHobby } from "./components/MyHobby";


//! Creating app - npx create-react-app [name of the app]
//* for starting, navigate to newly folder with command cd [name of the app]; then execute "npm start"

//! HOW to start app which is NOT generated by me
//* navigate to the app folder, execute command "npm install", and then execute "npm start"

//this is functional component
function App() {
  let number = 10;

  const element = <h1>Hello from JS react</h1>

  // function toUpperCaseName(user) {
  //   return user.toUpperCase();
  // }

  function toUpperCaseName(student) {
    return student.name.toUpperCase();
  }

  const student = {
    name: "Angela",
    lastName: "Antova",
    image: "https://cdnstorage.sendbig.com/unreal/female.webp"
  }

  function print() {
    console.log("I was clicked.")
  }

  //* when we want to use javascript in jsx we use {} brackets
  //! JSX e sintaksna ekstenzija na JS, no toa ne e nitu JS nitu html no ja ima mokjta na funkcionalnostite na dvete
  return (
    <div className="App">
      <h1 className="react-hello">Hello from React!</h1>

      <p>5+5 <Hobies/></p>
      <p>{5+5} <FavoriteHobby/></p>
      <p>{5 + 5 + number} result from this should be 20</p>
      {element}

      {/* <h1>Hello, {toUpperCaseName("martin")}</h1> */}
      <h1>Hello, {toUpperCaseName(student)}</h1>

      <a target="blank" href="http://google.com">Google</a>

      <img src={student.image} style={{ width: 300, height: 300 }}></img>
      <button onClick={print}>Click Me</button>

      <AppClass />
      <Hello />

      <hr></hr>
      <MyHobby />

    </div>
  );
}

export default App;